//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZarzadzanieUprawamiGUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class PraceZasoby
    {
        public int idPracaZasób { get; set; }
        public Nullable<int> idPracaPolowa { get; set; }
        public Nullable<int> idZasób { get; set; }
        public Nullable<int> ilośćZużytegoZasobu { get; set; }
    
        public virtual PracePolowe PracePolowe { get; set; }
        public virtual Zasób Zasób { get; set; }
    }
}
