//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZarzadzanieUprawamiGUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class PracePolowe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PracePolowe()
        {
            this.PraceZasoby = new HashSet<PraceZasoby>();
        }
    
        public int idPracaPolowa { get; set; }
        public Nullable<int> idPoleUprawa { get; set; }
        public Nullable<int> idWykonawca { get; set; }
        public Nullable<int> idPraca { get; set; }
        public Nullable<System.DateTime> dataWykonanejPracy { get; set; }
    
        public virtual Uprawy Uprawy { get; set; }
        public virtual RodzajePrac RodzajePrac { get; set; }
        public virtual Pracownicy Pracownicy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PraceZasoby> PraceZasoby { get; set; }
    }
}
