//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZarzadzanieUprawamiGUI
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;

    public partial class Rosliny
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rosliny()
        {
            this.Uprawy = new HashSet<Uprawy>();
        }



        public int idRoslina { get; set; }
        public Nullable<int> idGatunek { get; set; }
        public Nullable<int> idOdmiana { get; set; }
        public Nullable<int> idOkresowosc { get; set; }
        public Nullable<double> doplatyHa { get; set; }
        public Nullable<int> siewKgHa { get; set; }
        public Nullable<double> zbiorKgHa { get; set; }
        public Nullable<double> wartoscKg { get; set; }
        public Nullable<double> kosztOchronyHa { get; set; }
        public Nullable<double> koszNawozuHa { get; set; }
        public Nullable<double> kosztZbioruHa { get; set; }
    
        public virtual Gatunki Gatunki { get; set; }
        public virtual Odmiany Odmiany { get; set; }
        public virtual Okresowosci Okresowosci { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Uprawy> Uprawy { get; set; }
    }
}
