//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZarzadzanieUprawamiGUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uprawy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Uprawy()
        {
            this.PracePolowe = new HashSet<PracePolowe>();
            this.StanyUpraw = new HashSet<StanyUpraw>();
        }
    
        public int idUprawa { get; set; }
        public Nullable<int> idPole { get; set; }
        public Nullable<int> idRoslina { get; set; }
        public Nullable<System.DateTime> dataPoczatkowa { get; set; }
        public Nullable<System.DateTime> dataKoncowa { get; set; }
    
        public virtual Pola Pola { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PracePolowe> PracePolowe { get; set; }
        public virtual Rosliny Rosliny { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StanyUpraw> StanyUpraw { get; set; }
    }
}
